---
services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /docker_data/beszel:/beszel_data
    networks:
      - shared_bridge_1

networks:
  shared_bridge_1:
    external: true 